name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - feature/creating-gh-pages-deploment
      #change to main

jobs:
  build-application:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    #all the names should be their own job
    #like this build-application-upload-artifact:
    #make sure each step "needs" name of previous step
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install and build
        run: |
          cd ./Webproject/
          npm ci
          npm run build

  setup-gh-pages:
    runs-on: ubuntu-latest
    needs: build-application
    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2
        if: always()

  upload-artifact:
    runs-on: ubuntu-latest
    needs: setup-gh-pages
    steps:    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        if: always()
        with:
         path: Webproject/dist

  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    needs: upload-artifact       
    steps:     
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v1
        if: always()