name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - feature/creating-gh-pages-deploment
      #change to main

jobs:
  build-application-upload-artifact:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    #all the names should be their own job
    #like this build-application-upload-artifact:
    #make sure each step "needs" name of previous step

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install and build
        run: |
          cd ./Webproject/
          npm ci
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: Webproject/dist
          if-no-files-found: error

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2
        if: always()

      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v1
        if: always()