name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - feature/creating-gh-pages-deployment

jobs:
  build-application-upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install and build
        run: |
          cd ./Webproject/
          npm ci
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: Webproject/dist
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
