name: Build and deploy to github pages
on:
  pull_request:
    branches: [ "feature/creating-gh-pages-deploment" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout branch
      - uses: actions/checkout@v3

      - name: Install and build
        run: |
          cd ./Webproject/
          npm ci
          npm run build
    