name: Build and deploy to GitHub Pages

on:
  pull_request:
    branches:
      - feature/creating-gh-pages-deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install and build
        run: |
          cd ./Webproject/
          npm ci
          npm run build
