name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - feature/creating-gh-pages-deploment

jobs:
  build-application-upload-artifact:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install and build
        run: |
          cd ./Webproject/
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
         folder: Webproject/dist